config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => :registrations
	root 'home#index'
  resources :posts
  resources :categories
  resources :courses
  get '/users/sign_up', to: redirect('/#/home')
  get '/users/sign_out', to: redirect('/#/home')
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :category
  belongs_to :post
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :categorizations, dependent: :destroy
	has_many :posts, through: :categorizations

	def to_json(options = {})
		super(options.merge(include: :posts))		
	end
end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :categorizations, dependent: :destroy
	has_many :categories, through: :categorizations

	def category_list
		self.categories.map do |category|
			category.name
		end.join(", ")
	end

	def category_list=(categories_string)
		category_names = categories_string.split(",").map { |s| s.strip }.uniq
		new_or_found_categories = category_names.map { |name|  Category.find_or_create_by(name: name) }
		self.categories = new_or_found_categories
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_category, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:show]

	def index
		@categories = Category.all
		respond_to do |format|
      format.html
      format.json { render json: @categories}
    end
	end
	
	def show
		respond_to do |format|
      format.html
      format.json { render json: @category}
    end
	end

	def new
		@category = Category.new
		respond_to do |format|
      format.html
      format.json { render json: @category}
    end
	end

	def create
		@category = Category.new(category_params)		
		@category.save
		redirect_to category_path(@category)
	end

	def edit
		respond_to do |format|
      format.html
      format.json { render json: @category}
    end
	end

	def update
		@category.update(category_params)

		redirect_to category_path(@category)
	end

	def destroy
		@category.destroy

		redirect_to categories_path
	end

	private
	def set_category
		@category = Category.find(params[:id])
	end

	def category_params
		params.require(:category).permit(:name, :description, :inheritance, :attr, :attr_name)
	end
end


	

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	before_action :set_course, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index]

	def index
		@courses = Course.all
		respond_to do |format|
      format.html
      format.json { render json: @courses}
    end
	end
	
	def show
		respond_to do |format|
      format.html
      format.json { render json: @course}
    end
	end

	def new
		@course = Course.new
		respond_to do |format|
      format.html
      format.json { render json: @course}
    end
	end

	def create
		@course = Course.new(course_params)		
		@course.save
		redirect_to course_path(@course)
	end

	def edit
		respond_to do |format|
      format.html
      format.json { render json: @course}
    end
	end

	def update
		@course.update(course_params)

		redirect_to course_path(@course)
	end

	def destroy
		@course.destroy

		redirect_to course_path
	end

	private
	def set_course
		@course = Course.find(params[:id])
	end

	def course_params
		params.require(:course).permit(:name, :where, :university, :status)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:show]

	def index
		@posts = Post.all
		respond_to do |format|
      format.html
      format.json { render json: @posts}
    end
	end

	def show
		respond_to do |format|
      format.html
      format.json { render json: @post}
    end
	end

	def new
		@post = Post.new
		respond_to do |format|
      format.html
      format.json { render json: @post}
    end
	end

	def create
		@post = Post.new(post_params)		
		@post.save
		redirect_to post_path(@post)
	end

	def edit
		respond_to do |format|
      format.html
      format.json { render json: @post}
    end
	end

	def update
		@post.update(post_params)

		redirect_to post_path(@post)
	end

	def destroy
		@post.destroy

		redirect_to posts_path
	end

	private
	def set_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :body, :category_list, :source_code, :link, :image_url, :image_alt, :importance, :alttitle)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category, html: {class: "form-horizontal"}) do |f| %>
	<ul>
		<% @category.errors.full_messages.each do |error| %>
		<li><%= error %></li>
		<% end %>
	</ul>
	<div class="form-group">
		<%= f.label :name, class: "col-md-3 control-label" %>
		<div class="col-md-9">
			<%= f.text_field :name, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :description, class: "col-md-3 control-label" %>
		<div class="col-md-9">
			<%= f.text_area :description, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :inheritance, class: "col-md-3 control-label" %>
		<div class="col-md-9">
			<%= f.text_field :inheritance, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :attr, class: "col-md-3 control-label" %>
		<div class="col-md-9">
			<%= f.text_field :attr, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :attr_name, class: "col-md-3 control-label" %>
		<div class="col-md-9">
			<%= f.text_field :attr_name, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-offset-3 col-md-9">
			<%= f.submit "Submit", class: "btn btn-primary" %>	
		</div>
	</div>
<% end %>

app/views/categories/edit.html.erb
<h2 class="text-center m30">edit category</h2>

<%= render partial: 'form' %>

app/views/categories/index.html.erb
<h2 class="text-center m30">all categories</h2>

<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<%= link_to "new category", new_category_path, class: "btn btn-default mt30" %>		
		<ul class="list-unstyled index">
			<% @categories.each do |category| %>
			<li>
				<span class="glyphicon glyphicon-menu-right white"></span>
				ID: <%= category.id %> | <%= link_to category.name, category_path(category) %>
			</li>
			<% end %>
		</ul>
	</div>
</div>

app/views/categories/new.html.erb
<h2 class="text-center m30">create new category</h2>

<%= render partial: 'form' %>

app/views/categories/show.html.erb
<h2>Articles Tagged with <%= @category.name %></h2>

<%= link_to "edit", edit_category_path(@category) %>
<br>
<%= link_to 'delete', category_path(@category), method: :delete, data: { confirm: "really delete it?" } %>

<ul>
  <% @category.posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %></li>
  <% end %>
</ul>

app/views/courses/_form.html.erb
<%= form_for(@course, html: {class: "form-horizontal"}) do |f| %>
	<ul>
		<% @course.errors.full_messages.each do |error| %>
		<li><%= error %></li>
		<% end %>
	</ul>
	<div class="form-group">
		<%= f.label :name, class: "col-md-3 control-label" %>
		<div class="col-md-9">
			<%= f.text_field :name, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :where, class: "col-md-3 control-label" %>
		<div class="col-md-9">
			<%= f.text_field :where, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :university, class: "col-md-3 control-label" %>
		<div class="col-md-9">
			<%= f.text_field :university, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :status, class: "col-md-3 control-label" %>
		<div class="col-md-9">
			<%= f.text_field :status, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-offset-3 col-md-9">
			<%= f.submit "Submit", class: "btn btn-primary" %>	
		</div>
	</div>
<% end %>

app/views/courses/edit.html.erb
<h2 class="text-center m30">edit course</h2>

<%= render partial: 'form' %>

app/views/courses/index.html.erb
<h2 class="text-center m30">all courses</h2>

<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<ul class="list-unstyled index">
			<% @courses.each do |course| %>
			<li>
				<span class="glyphicon glyphicon-menu-right white"></span>
				ID: <%= course.id %> | <%= link_to course.name, course_path(course) %>
			</li>
			<% end %>
		</ul>

		<%= link_to "new course", new_course_path, class: "btn btn-default mt30" %>		
	</div>
</div>

app/views/courses/new.html.erb
<h2 class="text-center m30">create new course</h2>

<%= render partial: 'form' %>

app/views/courses/show.html.erb
<h2><%= @course.name %></h2>

<%= link_to "edit", edit_course_path(@course) %>
<br>
<%= link_to 'delete', course_path(@course), method: :delete, data: { confirm: "really delete it?" } %>

app/views/home/index.html.erb
<div ng-app="pwdd">
	<ui-view></ui-view>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resume | pwdd</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript">
  WebFontConfig = {
    google: { families: [ 'Inconsolata::latin' ] }
  };
  (function() {
    var wf = document.createElement('script');
    wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
      '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
    wf.type = 'text/javascript';
    wf.async = 'true';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(wf, s);
  })(); </script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= favicon_link_tag %>
  <%= favicon_link_tag 'apple-touch-icon-57x57.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '57x57' %>
  <%= favicon_link_tag 'apple-touch-icon-60x60.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '60x60' %>
  <%= favicon_link_tag 'apple-touch-icon-72x72.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '72x72' %>
  <%= favicon_link_tag 'apple-touch-icon-76x76.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '76x76' %>
  <%= favicon_link_tag 'apple-touch-icon-114x114.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '114x114' %>
  <%= favicon_link_tag 'apple-touch-icon-120x120.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '120x120' %>
  <%= favicon_link_tag 'apple-touch-icon-144x144.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '144x144' %>
  <%= favicon_link_tag 'apple-touch-icon-152x152.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '152x152' %>
  <%= favicon_link_tag 'apple-touch-icon-180x180.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '180x180' %>
  <%= favicon_link_tag 'favicon-32x32.png', type: 'image/png', sizes: '32x32' %>
  <%= favicon_link_tag 'favicon-96x96.png', type: 'image/png', sizes: '96x96' %>
  <%= favicon_link_tag 'favicon-16x16.png', type: 'image/png', sizes: '16x16' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Google Tag Manager -->
  <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PB4PT2"
  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-PB4PT2');</script>
  <!-- End Google Tag Manager -->
  <div class="container-fluid">
	  <%= yield %>
  </div>  
  <footer class="regular-screen">
    <ul class="list-inline pull-right">
      <li><a class="white" href="https://github.com/pwdd" target="_blank">Github |</a></li>
      <li><a class="white" href="https://www.linkedin.com/in/ainapinto" target="_blank">LinkedIn |</a></li>
      <li class="white">ainapinto[at]gmail[dot]com | </li>
      <% if user_signed_in? %>
      <li>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "white" %>
      </li>
      <% else %>
      <li>
        <%= link_to "Login", new_user_session_path, class: "white" %>
      </li>
      <% end %>
    </ul>
  </footer>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-68040402-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, html: {class: "form-horizontal"}) do |f| %>
	<ul>
		<% @post.errors.full_messages.each do |error| %>
		<li><%= error %></li>
		<% end %>
	</ul>
	<div class="form-group">
		<%= f.label :title, class: "col-md-3 control-label" %>
		<div class="col-md-9">
			<%= f.text_field :title, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :alttitle, class: "col-md-3 control-label" %>
		<div class="col-md-9">
			<%= f.text_field :alttitle, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :importance, class: "col-md-3 control-label" %>
		<div class="col-md-9">
			<%= f.text_field :importance, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :category_list, class: "col-md-3 control-label" %>
		<div class="col-md-9">
			<%= f.text_field :category_list, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :image_url, class: "col-md-3 control-label" %>
		<div class="col-md-9">
			<%= f.text_field :image_url, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :image_alt, class: "col-md-3 control-label" %>
		<div class="col-md-9">
			<%= f.text_field :image_alt, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :link, class: "col-md-3 control-label" %>
		<div class="col-md-9">
			<%= f.text_field :link, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :source_code, class: "col-md-3 control-label" %>
		<div class="col-md-9">
			<%= f.text_field :source_code, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :body, class: "col-md-3 control-label" %>
		<div class="col-md-9">
			<%= f.text_area :body, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-offset-3 col-md-9">
			<%= f.submit "Submit", class: "btn btn-primary" %>	
		</div>
	</div>
<% end %>

app/views/posts/edit.html.erb
<h1 class="text-center m30">edit post</h1>

<%= render partial: 'form' %>

app/views/posts/index.html.erb
<h1 class="text-center m30">all posts</h1>

<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<%= link_to "new post", new_post_path, class: "btn btn-default mt30" %>		
		<ul class="list-unstyled index">
			<% @posts.order(:importance).reverse_order.each do |post| %>
				<li>
					<span class="glyphicon glyphicon-menu-right white"></span>
					<%= post.importance %> | <%= link_to post.title, post_path(post) %>
				</li>
			<% end %>
		</ul>
	</div>
</div>

app/views/posts/new.html.erb
<h1 class="text-center m30">new post</h1>

<%= render partial: 'form' %>

app/views/posts/show.html.erb
<div class="row show-post">
	<div class="col-md-4 col-md-offset-4">
		<p>Title: <%= @post.title %></p>
		<p>
		Belongs to categories:
		<% @post.categories.each do |category| %>
		  <%= link_to category.name, category_path(category) %>
		<% end %>
		</p>

		<div class="btn-group mt30" role="group">
		<%= link_to 'delete', post_path(@post), method: :delete, 
		class: "btn btn-danger", data: { confirm: "really delete it?" } %>
		<%= link_to 'edit', edit_post_path(@post), class: "btn btn-success" %>
		<%= link_to "<span class='glyphicon glyphicon-backward'></span>back to posts list".html_safe, posts_path, class: "btn btn-default" %>
		</div>
	</div>
</div>

app/views/users/shared/_links.html.erb
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>